name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this matches your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc

      - name: Convert README.md to HTML
        run: |
          pandoc README.md -o README.html
          ls -alh  # List files to verify README.html is created

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./

